version: "3.9"
services:
  reservation :
    build: .\Reservation
    image: "reservation-img"
    container_name: reservation
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/reservation?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    networks:
      - unihub-network
    depends_on:
      - eureka
      - mysql-db

  eureka:
    build: .\EurekaD
    image: "eureka-img"
    container_name: "eureka"
    ports:
      - "8761:8761"
    hostname: discovery
    networks:
      - unihub-network

  gateway:
    build: .\ApiGateway
    image: "gateway-img"
    container_name: "gateway"
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - spring_cloud_gateway_routes[0]_id=reservation
      - spring_cloud_gateway_routes[0]_uri=http://Reservation:8081
      - spring_cloud_gateway_routes[0]_predicates[0]=Path=/reservation/**



    networks:
      - unihub-network
    depends_on:
      - eureka
      - reservation


  mysql-db:
    image: "mysql:5.6"
    container_name: "mysql-db"
    environment:
      - MYSQL_ROOT_PASSWORD=root #indisponsable pour la conteneurisation
    ports:
      - "3307:3306"
    restart: unless-stopped
    networks:
      - unihub-network

# Define a custom network with a specific name
networks:
  unihub-network:
    name: unihub-network

